enable_top_contributors:
  default: true
show_on:
  default: all
  type: enum
  choices:
    - top_menu
    - homepage
    - all
  description: refers to the <a href="/admin/site_settings/category/all_results?filter=top_menu">top menu site setting</a>
important_links:
  default: "All Unanswered Topics, https://discourse.kqhandmade.com/latest?max_posts=1 |Community Blog, # |Community Guidelines, # |Code of Conduct, https://discourse.kqhandmade.com/faq |Terms of Service, https://discourse.kqhandmade.com/tos |Privacy Policy, https://discourse.kqhandmade.com/privacy"
  type: list
  description: link names and urls for the important links
