enable_top_contributors:
  default: true
show_on:
  default: all
  type: enum
  choices:
    - top_menu
    - homepage
    - all
  description: refers to the <a href="/admin/site_settings/category/all_results?filter=top_menu">top menu site setting</a>
event_route:
  default: c/events/6
  type: text
  description: specifies an event route to display upcoming events